//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Threading.Tasks;

//namespace MyStatz.Models.MyProfile
//{
//    public class dummy
//    {
//    }

//    public enum HeroAvatars
//    {
//        antimage_sb = 1, 
//        axe_sb =2, 
//        bane_sb =3, 
//        bloodseeker_sb =4, 
//        crystal_maiden_sb =5, 
//        drow_ranger_sb =6, 
//        earthshaker_sb =7, 
//        juggernaut_sb =8, 
//        mirana_sb =9, 
//        nevermore_sb = 11, 
//        morphling_sb =10, 
//        phantom_lancer_sb =12, 
//        puck_sb =13, 
//        pudge_sb =14, 
//        razor_sb =15, 
//        sand_king_sb =16, 
//        storm_spirit_sb =17, 
//        sven_sb =18, 
//        tiny_sb =19, 
//        vengefulspirit_sb =20, 
//        windrunner_sb =21, 
//        zuus_sb =22, 
//        kunkka_sb =23, 
//        lina_sb =25, 
//        lich_sb =31, 
//        lion_sb =26, 
//        shadow_shaman_sb =27, 
//        slardar_sb =28, 
//        tidehunter_sb =29, 
//        witch_doctor_sb =30, 
//        riki_sb =32, 
//        enigma_sb =33, 
//        tinker_sb =34, 
//        sniper_sb =35, 
//        necrolyte_sb =36, 
//        warlock_sb =37, 
//        beastmaster_sb =38, 
//        queenofpain_sb =39, 
//        venomancer_sb =40, 
//        faceless_void_sb =41, 
//        skeleton_king_sb =42, 
//        death_prophet_sb =43, 
//        phantom_assassin_sb =44, 
//        pugna_sb =45, 
//        templar_assassin_sb =46, 
//        viper_sb =47, 
//        luna_sb =48, 
//        dragon_knight_sb =49, 
//        dazzle_sb =50, 
//        rattletrap_sb =51, 
//        leshrac_sb =52, 
//        furion_sb =53, 
//        life_stealer_sb =54, 
//        dark_seer_sb =55, 
//        clinkz_sb =56, 
//        omniknight_sb =57, 
//        enchantress_sb =58, 
//        huskar_sb =59, 
//        night_stalker_sb =60, 
//        broodmother_sb =61, 
//        bounty_hunter_sb =62, 
//        weaver_sb =63, 
//        jakiro_sb =64, 
//        batrider_sb =65, 
//        chen_sb =66, 
//        spectre_sb =67, 
//        doom_bringer_sb =69, 
//        ancient_apparition_sb =68, 
//        ursa_sb =70, 
//        spirit_breaker_sb =71, 
//        gyrocopter_sb =72, 
//        alchemist_sb =73, 
//        invoker_sb =74, 
//        silencer_sb =75, 
//        obsidian_destroyer_sb =76, 
//        lycan_sb =77, 
//        brewmaster_sb =78, 
//        shadow_demon_sb =79, 
//        lone_druid_sb =80, 
//        chaos_knight_sb =81, 
//        meepo_sb =82, 
//        treant_sb =83, 
//        ogre_magi_sb =84, 
//        undying_sb =85, 
//        rubick_sb =86, 
//        disruptor_sb =87, 
//        nyx_assassin_sb =88, 
//        naga_siren_sb =89, 
//        keeper_of_the_light_sb =90, 
//        wisp_sb =91, 
//        visage_sb =92, 
//        slark_sb =93, 
//        medusa_sb =94, 
//        troll_warlord_sb =95, 
//        centaur_sb =96, 
//        magnataur_sb =97, 
//        shredder_sb =98, 
//        bristleback_sb =99, 
//        tusk_sb =100,
//        skywrath_mage_sb=101
//    }

//}
//}
