using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyStatz.Models
{
    public class Players
    {
        public bool IsRadiant { get; set; }
        [JsonProperty("HeroId")]
        public HeroAvatar HeroImageId { get; set; }
        public int NumKills { get; set; }
        public int NumDeaths { get; set; }
        public int NumAssists { get; set; }
        public int LeaverStatus { get; set; }
        public int NumLastHits { get; set; }
        public int NumDenies { get; set; }
        public int GoldPerMinute { get; set; }
        public int ExperiencePerMinute { get; set; }
        public int Level { get; set; }
        public int Lane { get; set; }
        public int Role { get; set; }
        public int Imp { get; set; }
        public Item Item0Id { get; set; }
        public Item Item1Id { get; set; }
        public Item Item2Id { get; set; }
        public Item Item3Id { get; set; }
        public Item Item4Id { get; set; }
        public Item Item5Id { get; set; }
        public int RoamLane { get; set; }
        public bool IsVictory { get; set; }
        public int Networth { get; set; }
        public int Neutral0Id { get; set; }



    }
    public enum Item
    {
        emptyitembg_lg = 0,
        blink_lg = 1,
        blades_of_attack_lg = 2,
        broadsword_lg = 3,
        chainmail_lg = 4,
        claymore_lg = 5,
        helm_of_iron_will_lg = 6,
        javelin_lg = 7,
        mithril_hammer_lg = 8,
        platemail_lg = 9,
        quarterstaff_lg = 10,
        quelling_blade_lg = 11,
        ring_of_protection_lg = 12,
        stout_shield_lg = 182,
        gauntlets_lg = 13,
        slippers_lg = 14,
        mantle_lg = 15,
        branches_lg = 16,
        belt_of_strength_lg = 17,
        boots_of_elves_lg = 18,
        robe_lg = 19,
        circlet_lg = 20,
        ogre_axe_lg = 21,
        blade_of_alacrity_lg = 22,
        staff_of_wizardry_lg = 23,
        ultimate_orb_lg = 24,
        gloves_lg = 25,
        lifesteal_lg = 26,
        ring_of_regen_lg = 27,
        sobi_mask_lg = 28,
        boots_lg = 29,
        gem_lg = 30,
        cloak_lg = 31,
        talisman_of_evasion_lg = 32,
        cheese_lg = 33,
        magic_stick_lg = 34,
        recipe_magic_wand_lg = 35,
        magic_wand_lg = 36,
        ghost_lg = 37,
        clarity_lg = 38,
        flask_lg = 39,
        dust_lg = 40,
        bottle_lg = 41,
        ward_observer_lg = 42,
        ward_sentry_lg = 43,
        tango_lg = 44,
        courier_lg = 45,
        tpscroll_lg = 46,
        recipe_travel_boots_lg = 47,
        travel_boots_lg = 48,
        recipe_phase_boots_lg = 49,
        phase_boots_lg = 50,
        demon_edge_lg = 51,
        eagle_lg = 52,
        reaver_lg = 53,
        relic_lg = 54,
        hyperstone_lg = 55,
        ring_of_health_lg = 56,
        void_stone_lg = 57,
        mystic_staff_lg = 58,
        energy_booster_lg = 59,
        point_booster_lg = 60,
        vitality_booster_lg = 61,
        recipe_power_treads_lg = 62,
        power_treads_lg = 63,
        recipe_hand_of_midas_lg = 64,
        hand_of_midas_lg = 65,
        recipe_oblivion_staff_lg = 66,
        oblivion_staff_lg = 67,
        recipe_pers_lg = 68,
        pers_lg = 69,
        recipe_poor_mans_shield_lg = 70,
        poor_mans_shield_lg = 71,
        recipe_bracer_lg = 72,
        bracer_lg = 73,
        recipe_wraith_band_lg = 74,
        wraith_band_lg = 75,
        recipe_null_talisman_lg = 76,
        null_talisman_lg = 77,
        recipe_mekansm_lg = 78,
        mekansm_lg = 79,
        recipe_vladmir_lg = 80,
        vladmir_lg = 81,
        flying_courier_lg = 84,
        recipe_buckler_lg = 85,
        buckler_lg = 86,
        recipe_ring_of_basilius_lg = 87,
        ring_of_basilius_lg = 88,
        recipe_pipe_lg = 89,
        pipe_lg = 90,
        recipe_urn_of_shadows_lg = 91,
        urn_of_shadows_lg = 92,
        recipe_headdress_lg = 93,
        headdress_lg = 94,
        recipe_sheepstick_lg = 95,
        sheepstick_lg = 96,
        recipe_orchid_lg = 97,
        orchid_lg = 98,
        recipe_cyclone_lg = 99,
        cyclone_lg = 100,
        recipe_force_staff_lg = 101,
        force_staff_lg = 102,
        recipe_dagon_lg = 103,
        recipe_dagon_2_lg = 197,
        recipe_dagon_3_lg = 198,
        recipe_dagon_4_lg = 199,
        recipe_dagon_5_lg = 200,
        dagon_lg = 104,
        dagon_2_lg = 201,
        dagon_3_lg = 202,
        dagon_4_lg = 203,
        dagon_5_lg = 204,
        recipe_necronomicon_lg = 105,
        recipe_necronomicon_2_lg = 191,
        recipe_necronomicon_3_lg = 192,
        necronomicon_lg = 106,
        necronomicon_2_lg = 193,
        necronomicon_3_lg = 194,
        recipe_ultimate_scepter_lg = 107,
        ultimate_scepter_lg = 108,
        recipe_refresher_lg = 109,
        refresher_lg = 110,
        recipe_assault_lg = 111,
        assault_lg = 112,
        recipe_heart_lg = 113,
        heart_lg = 114,
        recipe_black_king_bar_lg = 115,
        black_king_bar_lg = 116,
        aegis_lg = 117,
        recipe_shivas_guard_lg = 118,
        shivas_guard_lg = 119,
        recipe_bloodstone_lg = 120,
        bloodstone_lg = 121,
        recipe_sphere_lg = 122,
        sphere_lg = 123,
        recipe_vanguard_lg = 124,
        vanguard_lg = 125,
        recipe_blade_mail_lg = 126,
        blade_mail_lg = 127,
        recipe_soul_booster_lg = 128,
        soul_booster_lg = 129,
        recipe_hood_of_defiance_lg = 130,
        hood_of_defiance_lg = 131,
        recipe_rapier_lg = 132,
        rapier_lg = 133,
        recipe_monkey_king_bar_lg = 134,
        monkey_king_bar_lg = 135,
        recipe_radiance_lg = 136,
        radiance_lg = 137,
        recipe_butterfly_lg = 138,
        butterfly_lg = 139,
        recipe_greater_crit_lg = 140,
        greater_crit_lg = 141,
        recipe_basher_lg = 142,
        basher_lg = 143,
        recipe_bfury_lg = 144,
        bfury_lg = 145,
        recipe_manta_lg = 146,
        manta_lg = 147,
        recipe_lesser_crit_lg = 148,
        lesser_crit_lg = 149,
        recipe_armlet_lg = 150,
        armlet_lg = 151,
        recipe_invis_sword_lg = 183,
        invis_sword_lg = 152,
        recipe_sange_and_yasha_lg = 153,
        sange_and_yasha_lg = 154,
        recipe_satanic_lg = 155,
        satanic_lg = 156,
        recipe_mjollnir_lg = 157,
        mjollnir_lg = 158,
        recipe_skadi_lg = 159,
        skadi_lg = 160,
        recipe_sange_lg = 161,
        sange_lg = 162,
        recipe_helm_of_the_dominator_lg = 163,
        helm_of_the_dominator_lg = 164,
        recipe_maelstrom_lg = 165,
        maelstrom_lg = 166,
        recipe_desolator_lg = 167,
        desolator_lg = 168,
        recipe_yasha_lg = 169,
        yasha_lg = 170,
        recipe_mask_of_madness_lg = 171,
        mask_of_madness_lg = 172,
        recipe_diffusal_blade_lg = 173,
        recipe_diffusal_blade_2_lg = 195,
        diffusal_blade_lg = 174,
        diffusal_blade_2_lg = 196,
        recipe_ethereal_blade_lg = 175,
        ethereal_blade_lg = 176,
        recipe_soul_ring_lg = 177,
        soul_ring_lg = 178,
        recipe_arcane_boots_lg = 179,
        arcane_boots_lg = 180,
        orb_of_venom_lg = 181,
        recipe_ancient_janggo_lg = 184,
        ancient_janggo_lg = 185,
        recipe_medallion_of_courage_lg = 186,
        medallion_of_courage_lg = 187,
        smoke_of_deceit_lg = 188,
        recipe_veil_of_discord_lg = 189,
        veil_of_discord_lg = 190,
        recipe_rod_of_atos_lg = 205,
        rod_of_atos_lg = 206,
        recipe_abyssal_blade_lg = 207,
        abyssal_blade_lg = 208,
        recipe_heavens_halberd_lg = 209,
        heavens_halberd_lg = 210,
        recipe_ring_of_aquila_lg = 211,
        ring_of_aquila_lg = 212,
        recipe_tranquil_boots_lg = 213,
        tranquil_boots_lg = 214,
        shadow_amulet_lg = 215,
        ward_dispenser_lg = 218,
        enchanted_mango_lg = 216,
        guardian_greaves_lg = 231,
        aether_lens_lg = 232,
        octarine_core_lg = 235,
        aeon_disk_lg = 256,
        glimmer_cape_lg = 254,
        keen_optic_lg = 287,
        grove_bow_lg = 288,
        quickening_charm_lg = 289,
        philosophers_stone_lg = 290,
        force_boots_lg = 291,
        desolator_2_lg = 292,
        phoenix_ash_lg = 293,
        seer_stone_lg = 294,
        elixer_lg = 302,
        vampire_fangs_lg = 297,
        craggy_coat_lg = 298,
        greater_faerie_fire_lg = 299,
        timeless_relic_lg = 300,
        mirror_shield_lg = 301,
        ironwood_tree_lg = 304,
        mango_tree_lg = 328,
        royal_jelly_lg = 305,
        pupils_gift_lg = 306,
        tome_of_aghanim_lg = 307,
        repair_kit_lg = 308,
        mind_breaker_lg = 309,
        third_eye_lg = 310,
        spell_prism_lg = 311,
        princes_knife_lg = 325,
        imp_claw_lg = 334,
        flicker_lg = 335,
        spy_gadget_lg = 336,
        spider_legs_lg = 326,
        vambrace_lg = 331,
        ocean_heart_lg = 354,
        broom_handle_lg = 355,
        trusty_shovel_lg = 356,
        nether_shawl_lg = 357,
        dragon_scale_lg = 358,
        essence_ring_lg = 359,
        clumsy_net_lg = 360,
        enchanted_quiver_lg = 361,










    }

    public enum HeroAvatar
    {
        antimage_sb = 1,
        axe_sb = 2,
        bane_sb = 3,
        bloodseeker_sb = 4,
        crystal_maiden_sb = 5,
        drow_ranger_sb = 6,
        earthshaker_sb = 7,
        juggernaut_sb = 8,
        mirana_sb = 9,
        nevermore_sb = 11,
        morphling_sb = 10,
        phantom_lancer_sb = 12,
        puck_sb = 13,
        pudge_sb = 14,
        razor_sb = 15,
        sand_king_sb = 16,
        storm_spirit_sb = 17,
        sven_sb = 18,
        tiny_sb = 19,
        vengefulspirit_sb = 20,
        windrunner_sb = 21,
        zuus_sb = 22,
        kunkka_sb = 23,
        lina_sb = 25,
        lich_sb = 31,
        lion_sb = 26,
        shadow_shaman_sb = 27,
        slardar_sb = 28,
        tidehunter_sb = 29,
        witch_doctor_sb = 30,
        riki_sb = 32,
        enigma_sb = 33,
        tinker_sb = 34,
        sniper_sb = 35,
        necrolyte_sb = 36,
        warlock_sb = 37,
        beastmaster_sb = 38,
        queenofpain_sb = 39,
        venomancer_sb = 40,
        faceless_void_sb = 41,
        skeleton_king_sb = 42,
        death_prophet_sb = 43,
        phantom_assassin_sb = 44,
        pugna_sb = 45,
        templar_assassin_sb = 46,
        viper_sb = 47,
        luna_sb = 48,
        dragon_knight_sb = 49,
        dazzle_sb = 50,
        rattletrap_sb = 51,
        leshrac_sb = 52,
        furion_sb = 53,
        life_stealer_sb = 54,
        dark_seer_sb = 55,
        clinkz_sb = 56,
        omniknight_sb = 57,
        enchantress_sb = 58,
        huskar_sb = 59,
        night_stalker_sb = 60,
        broodmother_sb = 61,
        bounty_hunter_sb = 62,
        weaver_sb = 63,
        jakiro_sb = 64,
        batrider_sb = 65,
        chen_sb = 66,
        spectre_sb = 67,
        doom_bringer_sb = 69,
        ancient_apparition_sb = 68,
        ursa_sb = 70,
        spirit_breaker_sb = 71,
        gyrocopter_sb = 72,
        alchemist_sb = 73,
        invoker_sb = 74,
        silencer_sb = 75,
        obsidian_destroyer_sb = 76,
        lycan_sb = 77,
        brewmaster_sb = 78,
        shadow_demon_sb = 79,
        lone_druid_sb = 80,
        chaos_knight_sb = 81,
        meepo_sb = 82,
        treant_sb = 83,
        ogre_magi_sb = 84,
        undying_sb = 85,
        rubick_sb = 86,
        disruptor_sb = 87,
        nyx_assassin_sb = 88,
        naga_siren_sb = 89,
        keeper_of_the_light_sb = 90,
        wisp_sb = 91,
        visage_sb = 92,
        slark_sb = 93,
        medusa_sb = 94,
        troll_warlord_sb = 95,
        centaur_sb = 96,
        magnataur_sb = 97,
        shredder_sb = 98,
        bristleback_sb = 99,
        tusk_sb = 100,
        skywrath_mage_sb = 101,
        abaddon_sb = 102,
        elder_titan_sb = 103,
        legion_commander_sb = 104,
        ember_spirit_sb = 106,
        earth_spirit_sb = 107,
        abyssal_underlord_sb = 108,
        terrorblade_sb = 109,
        phoenix_sb = 110,
        techies_sb = 105,
        oracle_sb = 111,
        winter_wyvern_sb = 112,
        arc_warden_sb = 113,
        monkey_king_sb = 114,
        dark_willow_sb = 119,
        pangolier_sb = 120,
        grimstroke_sb = 121,
        void_spirit_sb = 126,
        snapfire_sb = 128,
        mars_sb = 129


    }
}
